"""
porcelain.llm — provider-abstraction seam shared by both framework adapters.

This module is the single LLM boundary in agent-bench.  Both the LangGraph and
CrewAI adapters call the model exclusively through the :class:`LLMClient`
protocol defined here, so:

* tests can inject a :class:`FakeLLM` (offline, deterministic, free) and never
  touch the network or require an API key, and
* a real run reads ``ANTHROPIC_API_KEY`` and talks to Claude via the official
  ``anthropic`` SDK through :class:`RealAnthropicClient`.

Import-light contract
---------------------
This file lives in ``porcelain`` because it is the provider seam both adapters
share and tests inject.  It MUST stay import-light: ``anthropic`` is imported
*lazily* inside ``RealAnthropicClient.__init__`` (never at module top), so
``import porcelain.llm`` succeeds with no SDK installed and no API key, and
pytest collection stays green offline.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol, runtime_checkable


# ---------------------------------------------------------------------------
# LLMResponse
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class LLMResponse:
    """
    Uniform return value from :meth:`LLMClient.complete`.

    A frozen dataclass (rather than a bare tuple) so call sites read
    ``.text`` / ``.tokens_in`` / ``.tokens_out`` without positional ambiguity.

    Attributes
    ----------
    text : str
        The model's final text output (all text content blocks joined).
    tokens_in : int
        Input/prompt tokens consumed by this call.
    tokens_out : int
        Output/completion tokens generated by this call.
    """

    text: str
    tokens_in: int
    tokens_out: int


# ---------------------------------------------------------------------------
# LLMClient protocol
# ---------------------------------------------------------------------------

@runtime_checkable
class LLMClient(Protocol):
    """
    The one method both adapters use to call a model.

    Parameters
    ----------
    system : str
        System prompt (the grounding/citation instructions built by the
        adapter base class).
    messages : list[dict]
        Anthropic message-shape list, e.g. ``[{"role": "user", "content": ...}]``.
    model : str
        Model id from ``AgentSpec.model``; passed through verbatim by the real
        client and ignored by the fake.

    Returns
    -------
    LLMResponse
    """

    def complete(self, *, system: str, messages: list[dict], model: str) -> LLMResponse:
        ...


# ---------------------------------------------------------------------------
# RealAnthropicClient
# ---------------------------------------------------------------------------

class RealAnthropicClient:
    """
    Production :class:`LLMClient` backed by the Anthropic SDK.

    The ``anthropic`` import is lazy (inside ``__init__``) so that merely
    importing this module never requires the SDK.  Construction resolves
    ``ANTHROPIC_API_KEY`` from the environment unless an explicit key is given.

    Real calls are exercised only under the
    ``pytest.mark.skipif(no ANTHROPIC_API_KEY)`` integration test.
    """

    def __init__(self, api_key: str | None = None) -> None:
        import anthropic  # lazy: keeps module import-light and offline-safe

        if api_key is not None:
            self._client = anthropic.Anthropic(api_key=api_key)
        else:
            # Resolves ANTHROPIC_API_KEY (or ANTHROPIC_AUTH_TOKEN) from env.
            self._client = anthropic.Anthropic()

    def complete(self, *, system: str, messages: list[dict], model: str) -> LLMResponse:
        # Per the claude-api skill: adaptive thinking (NOT budget_tokens, which
        # 400s on modern models); no temperature/top_p.  spec.model is passed
        # through verbatim so the model id stays a spec concern.
        resp = self._client.messages.create(
            model=model,
            max_tokens=1024,
            system=system,
            messages=messages,
            thinking={"type": "adaptive"},
        )

        text = "".join(b.text for b in resp.content if b.type == "text")
        return LLMResponse(
            text=text,
            tokens_in=resp.usage.input_tokens,
            tokens_out=resp.usage.output_tokens,
        )


# ---------------------------------------------------------------------------
# FakeLLM
# ---------------------------------------------------------------------------

# Fixed token accounting so iteration/token assertions stay stable across runs.
_FAKE_TOKENS_IN = 100
_FAKE_TOKENS_OUT = 20


class FakeLLM:
    """
    Offline, deterministic, free :class:`LLMClient` — the default for unit tests.

    No network, no API key, no SDK import.  ``complete`` ignores ``model``,
    inspects the ``[doc_id: X]`` labels and the question text inside the passed
    ``system`` + ``messages``, and returns a canned grounded answer that:

    * always echoes at least one real ``[doc_id: X]`` label found in the
      provided context, so the deterministic citation extractor finds it and
      ``cites_corpus`` passes (→ GATE); and
    * for the on-call / stipend question specifically, returns text containing
      ``[doc_id: oncall-policy]`` plus the substring
      ``"$150 ... processed automatically through Workday"`` so golden q1 passes
      end to end.

    Token counts are fixed small integers so token/iteration assertions are
    stable.

    Parameters
    ----------
    doc_ids : set[str] | None
        Optional set of valid corpus doc_ids.  Not strictly required (the fake
        reads labels straight from the context), but accepted so callers can
        construct it with corpus knowledge if they wish.
    answers : dict[str, str] | None
        Optional rule table mapping a lowercase substring of the question to a
        canned answer string.  When a question contains one of these keys, the
        mapped answer is returned verbatim (it should itself contain a
        ``[doc_id: X]`` label).  Lets tests force a specific (or deliberately
        un-grounded) answer.
    """

    def __init__(
        self,
        doc_ids: set[str] | None = None,
        answers: dict[str, str] | None = None,
    ) -> None:
        self.doc_ids = doc_ids
        self.answers = answers or {}

    @staticmethod
    def _first_doc_id_label(text: str) -> str | None:
        """Return the first ``[doc_id: X]`` label found in *text*, or None."""
        import re

        m = re.search(r"\[doc_id:\s*([A-Za-z0-9._-]+)\s*\]", text)
        return m.group(0) if m else None

    def complete(self, *, system: str, messages: list[dict], model: str) -> LLMResponse:
        # Flatten all message text + system into one searchable blob.  Messages
        # use Anthropic shape: content is either a str or a list of blocks.
        blob_parts: list[str] = [system]
        question_parts: list[str] = []
        for msg in messages:
            content = msg.get("content", "")
            if isinstance(content, str):
                blob_parts.append(content)
                if msg.get("role") == "user":
                    question_parts.append(content)
            elif isinstance(content, list):
                for block in content:
                    if isinstance(block, dict) and block.get("type") == "text":
                        blob_parts.append(block.get("text", ""))
                        if msg.get("role") == "user":
                            question_parts.append(block.get("text", ""))
        blob = "\n".join(blob_parts)
        question = "\n".join(question_parts).lower()

        # 1. Explicit rule-table override (lets tests force any answer).
        for needle, canned in self.answers.items():
            if needle.lower() in question:
                return LLMResponse(
                    text=canned,
                    tokens_in=_FAKE_TOKENS_IN,
                    tokens_out=_FAKE_TOKENS_OUT,
                )

        # 2. On-call / stipend question — return the golden-q1 grounded answer
        #    iff the oncall-policy doc is actually in the provided context.
        is_oncall_q = (
            "on-call" in question
            or "on call" in question
            or "stipend" in question
        )
        if is_oncall_q and "[doc_id: oncall-policy]" in blob:
            text = (
                "The weekend on-call stipend is $150 per day, processed "
                "automatically through Workday at the end of the rotation week "
                "[doc_id: oncall-policy]."
            )
            return LLMResponse(
                text=text,
                tokens_in=_FAKE_TOKENS_IN,
                tokens_out=_FAKE_TOKENS_OUT,
            )

        # 3. Generic grounded fallback — echo the first real doc_id label from
        #    the context so cites_corpus passes for any question.
        label = self._first_doc_id_label(blob)
        if label is not None:
            text = f"Based on the retrieved context, here is the answer {label}."
        else:
            # No context at all — produce an ungrounded answer (no citation),
            # which the extractor will turn into empty citations → MAX_ITER.
            text = "I could not find grounding in the corpus for this question."

        return LLMResponse(
            text=text,
            tokens_in=_FAKE_TOKENS_IN,
            tokens_out=_FAKE_TOKENS_OUT,
        )
