"""
porcelain.llm — provider-abstraction seam shared by both framework adapters.

This module is the single LLM boundary in agent-bench.  Both the LangGraph and
CrewAI adapters call the model exclusively through the :class:`LLMClient`
protocol defined here, so:

* tests can inject a :class:`FakeLLM` (offline, deterministic, free) and never
  touch the network or require an API key, and
* a real run reads ``ANTHROPIC_API_KEY`` and talks to Claude via the official
  ``anthropic`` SDK through :class:`RealAnthropicClient`.

Import-light contract
---------------------
This file lives in ``porcelain`` because it is the provider seam both adapters
share and tests inject.  It MUST stay import-light: ``anthropic`` is imported
*lazily* inside ``RealAnthropicClient.__init__`` (never at module top), so
``import porcelain.llm`` succeeds with no SDK installed and no API key, and
pytest collection stays green offline.
"""

from __future__ import annotations

import json
import subprocess
from dataclasses import dataclass
from typing import Protocol, runtime_checkable


# ---------------------------------------------------------------------------
# LLMResponse
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class LLMResponse:
    """
    Uniform return value from :meth:`LLMClient.complete`.

    A frozen dataclass (rather than a bare tuple) so call sites read
    ``.text`` / ``.tokens_in`` / ``.tokens_out`` without positional ambiguity.

    Attributes
    ----------
    text : str
        The model's final text output (all text content blocks joined).
    tokens_in : int
        Input/prompt tokens consumed by this call.
    tokens_out : int
        Output/completion tokens generated by this call.
    """

    text: str
    tokens_in: int
    tokens_out: int


# ---------------------------------------------------------------------------
# LLMClient protocol
# ---------------------------------------------------------------------------

@runtime_checkable
class LLMClient(Protocol):
    """
    The one method both adapters use to call a model.

    Parameters
    ----------
    system : str
        System prompt (the grounding/citation instructions built by the
        adapter base class).
    messages : list[dict]
        Anthropic message-shape list, e.g. ``[{"role": "user", "content": ...}]``.
    model : str
        Model id from ``AgentSpec.model``; passed through verbatim by the real
        client and ignored by the fake.

    Returns
    -------
    LLMResponse
    """

    def complete(self, *, system: str, messages: list[dict], model: str) -> LLMResponse:
        ...


# ---------------------------------------------------------------------------
# RealAnthropicClient
# ---------------------------------------------------------------------------

class RealAnthropicClient:
    """
    Production :class:`LLMClient` backed by the Anthropic SDK.

    The ``anthropic`` import is lazy (inside ``__init__``) so that merely
    importing this module never requires the SDK.  Construction resolves
    ``ANTHROPIC_API_KEY`` from the environment unless an explicit key is given.

    Real calls are exercised only under the
    ``pytest.mark.skipif(no ANTHROPIC_API_KEY)`` integration test.
    """

    def __init__(self, api_key: str | None = None) -> None:
        import anthropic  # lazy: keeps module import-light and offline-safe

        if api_key is not None:
            self._client = anthropic.Anthropic(api_key=api_key)
        else:
            # Resolves ANTHROPIC_API_KEY (or ANTHROPIC_AUTH_TOKEN) from env.
            self._client = anthropic.Anthropic()

    def complete(self, *, system: str, messages: list[dict], model: str) -> LLMResponse:
        # Per the claude-api skill: adaptive thinking (NOT budget_tokens, which
        # 400s on modern models); no temperature/top_p.  spec.model is passed
        # through verbatim so the model id stays a spec concern.
        resp = self._client.messages.create(
            model=model,
            max_tokens=1024,
            system=system,
            messages=messages,
            thinking={"type": "adaptive"},
        )

        text = "".join(b.text for b in resp.content if b.type == "text")
        return LLMResponse(
            text=text,
            tokens_in=resp.usage.input_tokens,
            tokens_out=resp.usage.output_tokens,
        )


# ---------------------------------------------------------------------------
# ClaudeCodeClient
# ---------------------------------------------------------------------------

# Default location of the REAL claude binary on this machine.  The `claude`
# shell alias points at `happy`; we must call the real binary directly to get
# headless ``-p`` behaviour, so the path is the binary, not the alias.
_DEFAULT_CLAUDE_BINARY = "/Users/cybermelon/.nvm/versions/node/v23.8.0/bin/claude"


class ClaudeCodeClient:
    """
    Offline-capable :class:`LLMClient` backed by headless Claude Code (``claude -p``).

    Why this exists
    ---------------
    agent-bench is a demonstration of a *model/framework eval platform*: the
    model is a swappable detail behind the :class:`LLMClient` seam.  To run with
    no API key, this client shells out to the real ``claude`` binary in headless
    mode (``claude -p "<prompt>" --max-turns 1``), which prints the model's text
    to stdout.

    Persona axis
    ------------
    When constructed with a ``persona_prompt`` (a CL4R1T4S system prompt that
    makes Claude *act like* another product, e.g. Cursor or ChatGPT), that text
    is prepended to the composed prompt.  These are labelled honestly as
    ``claude-as-<persona>`` everywhere — they are NOT real GPT/Gemini calls.

    Token accounting
    ----------------
    Plain ``claude -p`` text output carries no usage block, so ``tokens_in`` /
    ``tokens_out`` are **ESTIMATES** computed with a ``len(...)//4`` heuristic
    (~4 chars/token).  When ``use_json_usage=True`` the client tries
    ``--output-format json`` and, if the JSON parses and exposes a usage block,
    reports the *real* counts; otherwise it transparently falls back to the
    estimate.  Treat the estimate as indicative only — it is not billed usage.

    Parameters
    ----------
    binary : str
        Absolute path to the real claude binary.  Defaults to the known
        install path on this machine.
    persona_prompt : str | None
        Optional persona/system text prepended to every composed prompt.
    timeout_s : float
        Per-call subprocess timeout in seconds (default 120).
    use_json_usage : bool
        If True, request ``--output-format json`` and parse real usage when
        available, falling back to the char-based estimate on any failure.
    """

    def __init__(
        self,
        binary: str = _DEFAULT_CLAUDE_BINARY,
        persona_prompt: str | None = None,
        timeout_s: float = 120,
        use_json_usage: bool = False,
    ) -> None:
        self.binary = binary
        self.persona_prompt = persona_prompt
        self.timeout_s = timeout_s
        self.use_json_usage = use_json_usage

    # -- prompt composition --------------------------------------------------

    @staticmethod
    def _user_text(messages: list[dict]) -> str:
        """Flatten the user-message content into a single string.

        Accepts the Anthropic message shape where ``content`` is either a plain
        string or a list of content blocks; only ``text`` blocks contribute.
        """
        parts: list[str] = []
        for msg in messages:
            content = msg.get("content", "")
            if isinstance(content, str):
                parts.append(content)
            elif isinstance(content, list):
                for block in content:
                    if isinstance(block, dict) and block.get("type") == "text":
                        parts.append(block.get("text", ""))
        return "\n".join(p for p in parts if p)

    def _compose_prompt(self, *, system: str, messages: list[dict]) -> str:
        """Build the single prompt string: persona + system + user content."""
        sections: list[str] = []
        if self.persona_prompt:
            sections.append(self.persona_prompt)
        if system:
            sections.append(system)
        user = self._user_text(messages)
        if user:
            sections.append(user)
        return "\n\n".join(sections)

    def _argv(self, prompt: str) -> list[str]:
        """The exact argv passed to subprocess.run for *prompt*."""
        argv = [self.binary, "-p", prompt, "--max-turns", "1"]
        if self.use_json_usage:
            argv += ["--output-format", "json"]
        return argv

    # -- LLMClient.complete --------------------------------------------------

    def complete(self, *, system: str, messages: list[dict], model: str) -> LLMResponse:
        # ``model`` is accepted for protocol parity but not forwarded: the
        # headless binary uses whatever model the local Claude Code is
        # configured with.  The persona — not the model id — is the axis here.
        prompt = self._compose_prompt(system=system, messages=messages)
        argv = self._argv(prompt)

        try:
            proc = subprocess.run(
                argv,
                capture_output=True,
                text=True,
                timeout=self.timeout_s,
            )
        except subprocess.TimeoutExpired as exc:
            raise RuntimeError(
                f"claude -p timed out after {self.timeout_s}s "
                f"(binary={self.binary!r})"
            ) from exc

        if proc.returncode != 0:
            raise RuntimeError(
                f"claude -p exited {proc.returncode} "
                f"(binary={self.binary!r}): {proc.stderr.strip()[:500]}"
            )

        stdout = proc.stdout

        # JSON path: parse real usage when requested and available; otherwise
        # fall back to the estimate so a JSON-shape change never breaks a run.
        if self.use_json_usage:
            parsed = self._try_parse_json_usage(stdout)
            if parsed is not None:
                return parsed

        text = stdout.strip()
        # ESTIMATE ONLY: ~4 chars/token. Plain `claude -p` returns no usage.
        return LLMResponse(
            text=text,
            tokens_in=len(prompt) // 4,
            tokens_out=len(text) // 4,
        )

    @staticmethod
    def _try_parse_json_usage(stdout: str) -> LLMResponse | None:
        """Parse ``--output-format json`` output into an LLMResponse.

        Returns None (caller falls back to the estimate) if the payload does not
        parse or does not expose the expected text/usage fields.
        """
        try:
            payload = json.loads(stdout)
        except (json.JSONDecodeError, ValueError):
            return None
        if not isinstance(payload, dict):
            return None

        # claude -p --output-format json shape: top-level "result" holds the
        # text; "usage" holds input/output token counts when present.
        text = payload.get("result")
        if not isinstance(text, str):
            return None
        usage = payload.get("usage")
        if not isinstance(usage, dict):
            return None
        tin = usage.get("input_tokens")
        tout = usage.get("output_tokens")
        if not isinstance(tin, int) or not isinstance(tout, int):
            return None
        return LLMResponse(text=text.strip(), tokens_in=tin, tokens_out=tout)


# ---------------------------------------------------------------------------
# FakeLLM
# ---------------------------------------------------------------------------

# Fixed token accounting so iteration/token assertions stay stable across runs.
_FAKE_TOKENS_IN = 100
_FAKE_TOKENS_OUT = 20


class FakeLLM:
    """
    Offline, deterministic, free :class:`LLMClient` — the default for unit tests.

    No network, no API key, no SDK import.  ``complete`` ignores ``model``,
    inspects the ``[doc_id: X]`` labels and the question text inside the passed
    ``system`` + ``messages``, and returns a canned grounded answer that:

    * always echoes at least one real ``[doc_id: X]`` label found in the
      provided context, so the deterministic citation extractor finds it and
      ``cites_corpus`` passes (→ GATE); and
    * for the on-call / stipend question specifically, returns text containing
      ``[doc_id: oncall-policy]`` plus the substring
      ``"$150 ... processed automatically through Workday"`` so golden q1 passes
      end to end.

    Token counts are fixed small integers so token/iteration assertions are
    stable.

    Parameters
    ----------
    doc_ids : set[str] | None
        Optional set of valid corpus doc_ids.  Not strictly required (the fake
        reads labels straight from the context), but accepted so callers can
        construct it with corpus knowledge if they wish.
    answers : dict[str, str] | None
        Optional rule table mapping a lowercase substring of the question to a
        canned answer string.  When a question contains one of these keys, the
        mapped answer is returned verbatim (it should itself contain a
        ``[doc_id: X]`` label).  Lets tests force a specific (or deliberately
        un-grounded) answer.
    """

    def __init__(
        self,
        doc_ids: set[str] | None = None,
        answers: dict[str, str] | None = None,
    ) -> None:
        self.doc_ids = doc_ids
        self.answers = answers or {}

    @staticmethod
    def _first_doc_id_label(text: str) -> str | None:
        """Return the first ``[doc_id: X]`` label found in *text*, or None."""
        import re

        m = re.search(r"\[doc_id:\s*([A-Za-z0-9._-]+)\s*\]", text)
        return m.group(0) if m else None

    def complete(self, *, system: str, messages: list[dict], model: str) -> LLMResponse:
        # Flatten all message text + system into one searchable blob.  Messages
        # use Anthropic shape: content is either a str or a list of blocks.
        blob_parts: list[str] = [system]
        question_parts: list[str] = []
        for msg in messages:
            content = msg.get("content", "")
            if isinstance(content, str):
                blob_parts.append(content)
                if msg.get("role") == "user":
                    question_parts.append(content)
            elif isinstance(content, list):
                for block in content:
                    if isinstance(block, dict) and block.get("type") == "text":
                        blob_parts.append(block.get("text", ""))
                        if msg.get("role") == "user":
                            question_parts.append(block.get("text", ""))
        blob = "\n".join(blob_parts)
        question = "\n".join(question_parts).lower()

        # 1. Explicit rule-table override (lets tests force any answer).
        for needle, canned in self.answers.items():
            if needle.lower() in question:
                return LLMResponse(
                    text=canned,
                    tokens_in=_FAKE_TOKENS_IN,
                    tokens_out=_FAKE_TOKENS_OUT,
                )

        # 2. On-call / stipend question — return the golden-q1 grounded answer
        #    iff the oncall-policy doc is actually in the provided context.
        is_oncall_q = (
            "on-call" in question
            or "on call" in question
            or "stipend" in question
        )
        if is_oncall_q and "[doc_id: oncall-policy]" in blob:
            text = (
                "The weekend on-call stipend is $150 per day, processed "
                "automatically through Workday at the end of the rotation week "
                "[doc_id: oncall-policy]."
            )
            return LLMResponse(
                text=text,
                tokens_in=_FAKE_TOKENS_IN,
                tokens_out=_FAKE_TOKENS_OUT,
            )

        # 3. Generic grounded fallback — echo the first real doc_id label from
        #    the context so cites_corpus passes for any question.
        label = self._first_doc_id_label(blob)
        if label is not None:
            text = f"Based on the retrieved context, here is the answer {label}."
        else:
            # No context at all — produce an ungrounded answer (no citation),
            # which the extractor will turn into empty citations → MAX_ITER.
            text = "I could not find grounding in the corpus for this question."

        return LLMResponse(
            text=text,
            tokens_in=_FAKE_TOKENS_IN,
            tokens_out=_FAKE_TOKENS_OUT,
        )
